services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gov-web-library
    ports:
      - "3100:3100"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3100
    restart: unless-stopped
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
